//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	


using System;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Collections.Generic;
using Events.Entities;

namespace Events.Repositories
{
	public partial class LocationRepository : Repository<Location>
	{
	
		public LocationRepository(DbContext ctx, bool noTracking = true) : base(ctx, noTracking)
		{
		}
			
			
		public IEnumerable<Location> FetchAllLocations(params Expression<Func<Location, object>>[] paths)
		{
			return IRepository.FetchAll(paths);
		}
	
		public IEnumerable<Location> FetchAllLocations(Func<IQueryable<Location>, IOrderedQueryable<Location>> orderBy, int pageSize, int pageNumber, params Expression<Func<Location, object>>[] paths)
		{
	        return IRepository.FetchAll(orderBy, pageSize, pageNumber, paths);
		}
	
		public IEnumerable<Location> FetchManyLocations(Expression<Func<Location, bool>> predicate, params Expression<Func<Location, object>>[] paths)
		{
			return IRepository.FetchMany(predicate, paths);
		}
	
	    public IEnumerable<Location> FetchManyLocations(Expression<Func<Location, bool>> predicate, Func<IQueryable<Location>, IOrderedQueryable<Location>> orderBy, int pageSize, int pageNumber, params Expression<Func<Location, object>>[] paths)
	    {
	        return IRepository.FetchMany(predicate, orderBy, pageSize, pageNumber, paths);
	    }
	
		public Location FetchLocation(Expression<Func<Location, bool>> predicate, params Expression<Func<Location, object>>[] paths)
		{
			return IRepository.Fetch(predicate, paths);
		}
	
		
	
		public Location FetchLocation(params object[] keys)
		{
			return IRepository.Fetch(keys);
		}
	
		
	
		public IEnumerable<Location> SqlQuery(string esqlText, object[] Parameters)
		{
			return IRepository.SqlQuery(esqlText, Parameters);
		}
	
		public void AddLocation(Location entity)
		{
			 IRepository.Add(entity);
		}
	
		
	
		public void UpdateLocation(Location entity)
		{
			 IRepository.Update(entity, e => e.Id == entity.Id);
		}
	
		
	
		public void DeleteLocation(Location entity)
		{
			 IRepository.Delete(entity, e => e.Id == entity.Id);
		}
	
		
	
	}
	
}
