//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	


using System;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Collections.Generic;
using Events.Entities;

namespace Events.Repositories
{
	public partial class SessionRepository : Repository<Session>
	{
	
		public SessionRepository(DbContext ctx, bool noTracking = true) : base(ctx, noTracking)
		{
		}
			
			
		public IEnumerable<Session> FetchAllSessions(params Expression<Func<Session, object>>[] paths)
		{
			return IRepository.FetchAll(paths);
		}
	
		public IEnumerable<Session> FetchAllSessions(Func<IQueryable<Session>, IOrderedQueryable<Session>> orderBy, int pageSize, int pageNumber, params Expression<Func<Session, object>>[] paths)
		{
	        return IRepository.FetchAll(orderBy, pageSize, pageNumber, paths);
		}
	
		public IEnumerable<Session> FetchManySessions(Expression<Func<Session, bool>> predicate, params Expression<Func<Session, object>>[] paths)
		{
			return IRepository.FetchMany(predicate, paths);
		}
	
	    public IEnumerable<Session> FetchManySessions(Expression<Func<Session, bool>> predicate, Func<IQueryable<Session>, IOrderedQueryable<Session>> orderBy, int pageSize, int pageNumber, params Expression<Func<Session, object>>[] paths)
	    {
	        return IRepository.FetchMany(predicate, orderBy, pageSize, pageNumber, paths);
	    }
	
		public Session FetchSession(Expression<Func<Session, bool>> predicate, params Expression<Func<Session, object>>[] paths)
		{
			return IRepository.Fetch(predicate, paths);
		}
	
		
	
		public Session FetchSession(params object[] keys)
		{
			return IRepository.Fetch(keys);
		}
	
		
	
		public IEnumerable<Session> SqlQuery(string esqlText, object[] Parameters)
		{
			return IRepository.SqlQuery(esqlText, Parameters);
		}
	
		public void AddSession(Session entity)
		{
			 IRepository.Add(entity);
		}
	
		
	
		public void UpdateSession(Session entity)
		{
			 IRepository.Update(entity, e => e.Id == entity.Id);
		}
	
		
	
		public void DeleteSession(Session entity)
		{
			 IRepository.Delete(entity, e => e.Id == entity.Id);
		}
	
		
	
	}
	
}
