//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Events.EF;
using Events.Entities;
using Events.Common;

namespace Events.Repositories
{
	public partial class VoterRepository : Repository<Voter>
	{
	
		public VoterRepository(DbContext ctx, bool noTracking = true) : base(ctx, noTracking)
		{
		}
			
			
		public IEnumerable<Voter> FetchAllVoters(params Expression<Func<Voter, object>>[] paths)
		{
			return _iRepository.FetchAll(paths);
		}
	
		public IEnumerable<Voter> FetchAllVoters(Func<IQueryable<Voter>, IOrderedQueryable<Voter>> orderBy, int pageSize, int pageNumber, params Expression<Func<Voter, object>>[] paths)
		{
	        return _iRepository.FetchAll(orderBy, pageSize, pageNumber, paths);
		}
	
		public IEnumerable<Voter> FetchManyVoters(Expression<Func<Voter, bool>> predicate, params Expression<Func<Voter, object>>[] paths)
		{
			return _iRepository.FetchMany(predicate, paths);
		}
	
	    public IEnumerable<Voter> FetchManyVoters(Expression<Func<Voter, bool>> predicate, Func<IQueryable<Voter>, IOrderedQueryable<Voter>> orderBy, int pageSize, int pageNumber, params Expression<Func<Voter, object>>[] paths)
	    {
	        return _iRepository.FetchMany(predicate, orderBy, pageSize, pageNumber, paths);
	    }
	
		public Voter FetchVoter(Expression<Func<Voter, bool>> predicate, params Expression<Func<Voter, object>>[] paths)
		{
			return _iRepository.Fetch(predicate, paths);
		}
	
		
	
		public Voter FetchVoter(params object[] keys)
		{
			return _iRepository.Fetch(keys);
		}
	
		
	
		public IEnumerable<Voter> SqlQuery(string esqlText, object[] Parameters)
		{
			return _iRepository.SqlQuery(esqlText, Parameters);
		}
	
		public void AddVoter(Voter entity)
		{
			 _iRepository.Add(entity);
		}
	
		
	
		public void UpdateVoter(Voter entity)
		{
			 _iRepository.Update(entity, e => e.Id == entity.Id);
		}
	
		
	
		public void DeleteVoter(Voter entity)
		{
			 _iRepository.Delete(entity, e => e.Id == entity.Id);
		}
	
		
	
	}
	
}
