/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using Repository.Models;
using System;

namespace Repository.ViewModels
{
    public class CountryViewModel : IViewModel<Country>
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Country ToModel()
        {
            return new Country()
            {
                Id = Id,
                Name = Name
            };
        }

        public void FromModel(Country model)
        {
            Id = model.Id;
            Name = model.Name;
        }

        public void UpdateModel(Country model)
        {
            model.Id = Id;
            model.Name = Name;
        }

        public object[] GetKeys()
        {
            return new object[] { Id };
        }
    }
}