/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

namespace Repository.ViewModels
{
    public interface IViewModel<TModel> where TModel : class
        {
            TModel ToModel();
            void FromModel(TModel model);
            void UpdateModel(TModel model);
            object[] GetKeys();
        }
}