//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Entities
{
    using EF;
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Infrastructure.Interception;
    //public class Interceptor : IDbCommandInterceptor
    //{
    //    public void NonQueryExecuted(DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
    //    {
    //        throw new NotImplementedException();
    //    }

    //    public void NonQueryExecuting(DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
    //    {
    //        throw new NotImplementedException();
    //    }

    //    public void ReaderExecuted(DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
    //    {
    //        throw new NotImplementedException();
    //    }

    //    public void ReaderExecuting(DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
    //    {
    //        int x = 0;
    //    }

    //    public void ScalarExecuted(DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
    //    {
    //        throw new NotImplementedException();
    //    }

    //    public void ScalarExecuting(DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
    //    {
    //        throw new NotImplementedException();
    //    }
    //}
    public partial class LinqTestEntities : DbContext
    {
        public LinqTestEntities()
            : base("name=LinqTestEntities")
        {
            this.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
            DbInterception.Add(new LogCommandInterceptor());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
    }
}
