//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Voters = new HashSet<Voter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Presenter { get; set; }
        public int DurationId { get; set; }
        public int LevelId { get; set; }
        public string Abstract { get; set; }
        public int EventId { get; set; }
    
        public virtual Duration Duration { get; set; }
        public virtual Event Event { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voter> Voters { get; set; }
    }
}
